[0] = { 3, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, SIZE_T} }	/* sys_read */
[1] = { 3, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, SIZE_T} }	/* sys_write */
[2] = { 3, {PT, CHAR}, {ST, INT}, {ST, UMODE_T} }	/* sys_open */
[3] = { 1, {ST, UNSIGNED INT} }	/* sys_close */
[4] = { 2, {PT, CHAR}, {PT, STRUCT __OLD_KERNEL_STAT} }	/* sys_stat */
[5] = { 2, {ST, UNSIGNED INT}, {PT, STRUCT __OLD_KERNEL_STAT} }	/* sys_fstat */
[6] = { 2, {PT, CHAR}, {PT, STRUCT __OLD_KERNEL_STAT} }	/* sys_lstat */
[7] = { 3, {PT, STRUCT POLLFD}, {ST, UNSIGNED INT}, {ST, INT} }	/* sys_poll */
[8] = { 3, {ST, UNSIGNED INT}, {ST, OFF_T}, {ST, UNSIGNED INT} }	/* sys_lseek */
[9] = { 3, {ST, UNSIGNED INT}, {ST, OFF_T}, {ST, UNSIGNED INT} }	/* sys_mmap */
[10] = { 3, {ST, UNSIGNED LONG}, {ST, SIZE_T}, {ST, UNSIGNED LONG} }	/* sys_mprotect */
[11] = { 2, {ST, UNSIGNED LONG}, {ST, SIZE_T} }	/* sys_munmap */
[12] = { 1, {ST, UNSIGNED LONG} }	/* sys_brk */
[13] = { 4, {ST, INT}, {PT, STRUCT SIGACTION}, {PT, STRUCT SIGACTION}, {ST, SIZE_T} }	/* sys_rt_sigaction */
[14] = { 4, {ST, INT}, {PT, SIGSET_T}, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_rt_sigprocmask */
[15] = { 4, {ST, INT}, {PT, SIGSET_T}, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_rt_sigreturn */
[16] = { 3, {ST, UNSIGNED INT}, {ST, UNSIGNED INT}, {ST, UNSIGNED LONG} }	/* sys_ioctl */
[17] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, SIZE_T}, {ST, LOFF_T} }	/* sys_pread64 */
[18] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, SIZE_T}, {ST, LOFF_T} }	/* sys_pwrite64 */
[19] = { 3, {ST, UNSIGNED LONG}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG} }	/* sys_readv */
[20] = { 3, {ST, UNSIGNED LONG}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG} }	/* sys_writev */
[21] = { 2, {PT, CHAR}, {ST, INT} }	/* sys_access */
[22] = { 1, {PT, INT} }	/* sys_pipe */
[23] = { 5, {ST, INT}, {PT, FD_SET}, {PT, FD_SET}, {PT, FD_SET}, {PT, STRUCT TIMEVAL} }	/* sys_select */
[24] = { 1, {ST, VOID} }	/* sys_sched_yield */
[25] = { 5, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_mremap */
[26] = { 3, {ST, UNSIGNED LONG}, {ST, SIZE_T}, {ST, INT} }	/* sys_msync */
[27] = { 3, {ST, UNSIGNED LONG}, {ST, SIZE_T}, {PT, UNSIGNED CHAR} }	/* sys_mincore */
[28] = { 3, {ST, UNSIGNED LONG}, {ST, SIZE_T}, {ST, INT} }	/* sys_madvise */
[29] = { 3, {ST, KEY_T}, {ST, SIZE_T}, {ST, INT} }	/* sys_shmget */
[30] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_shmat */
[31] = { 3, {ST, INT}, {ST, INT}, {PT, STRUCT SHMID_DS} }	/* sys_shmctl */
[32] = { 1, {ST, UNSIGNED INT} }	/* sys_dup */
[33] = { 2, {ST, UNSIGNED INT}, {ST, UNSIGNED INT} }	/* sys_dup2 */
[34] = { 1, {ST, VOID} }	/* sys_pause */
[35] = { 2, {PT, STRUCT TIMESPEC}, {PT, STRUCT TIMESPEC} }	/* sys_nanosleep */
[36] = { 2, {ST, INT}, {PT, STRUCT ITIMERVAL} }	/* sys_getitimer */
[37] = { 1, {ST, UNSIGNED INT} }	/* sys_alarm */
[38] = { 3, {ST, INT}, {PT, STRUCT ITIMERVAL}, {PT, STRUCT ITIMERVAL} }	/* sys_setitimer */
[39] = { 1, {ST, VOID} }	/* sys_getpid */
[40] = { 4, {ST, INT}, {ST, INT}, {PT, OFF_T}, {ST, SIZE_T} }	/* sys_sendfile */
[41] = { 3, {ST, INT}, {ST, INT}, {ST, INT} }	/* sys_socket */
[42] = { 3, {ST, INT}, {PT, STRUCT SOCKADDR}, {ST, INT} }	/* sys_connect */
[43] = { 3, {ST, INT}, {PT, STRUCT SOCKADDR}, {PT, INT} }	/* sys_accept */
[44] = { 6, {ST, INT}, {PT, VOID}, {ST, SIZE_T}, {ST, UNSIGNED}, {PT, STRUCT SOCKADDR}, {ST, INT} }	/* sys_sendto */
[45] = { 6, {ST, INT}, {PT, VOID}, {ST, SIZE_T}, {ST, UNSIGNED}, {PT, STRUCT SOCKADDR}, {PT, INT} }	/* sys_recvfrom */
[46] = { 3, {ST, INT}, {PT, STRUCT MSGHDR}, {ST, UNSIGNED} }	/* sys_sendmsg */
[47] = { 3, {ST, INT}, {PT, STRUCT MSGHDR}, {ST, UNSIGNED} }	/* sys_recvmsg */
[48] = { 2, {ST, INT}, {ST, INT} }	/* sys_shutdown */
[49] = { 3, {ST, INT}, {PT, STRUCT SOCKADDR}, {ST, INT} }	/* sys_bind */
[50] = { 2, {ST, INT}, {ST, INT} }	/* sys_listen */
[51] = { 3, {ST, INT}, {PT, STRUCT SOCKADDR}, {PT, INT} }	/* sys_getsockname */
[52] = { 3, {ST, INT}, {PT, STRUCT SOCKADDR}, {PT, INT} }	/* sys_getpeername */
[53] = { 4, {ST, INT}, {ST, INT}, {ST, INT}, {PT, INT} }	/* sys_socketpair */
[54] = { 5, {ST, INT}, {ST, INT}, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_setsockopt */
[55] = { 5, {ST, INT}, {ST, INT}, {ST, INT}, {PT, CHAR}, {PT, INT} }	/* sys_getsockopt */
[56] = { 6, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, INT}, {PT, INT}, {PT, INT}, {ST, INT} }	/* sys_clone */
[57] = { 1, {ST, VOID} }	/* sys_fork */
[58] = { 1, {ST, VOID} }	/* sys_vfork */
[59] = { 3, {PT, CHAR}, {PT, CHAR}, {PT, CHAR} }	/* sys_execve */
[60] = { 1, {ST, INT} }	/* sys_exit */
[61] = { 4, {ST, PID_T}, {PT, INT}, {ST, INT}, {PT, STRUCT RUSAGE} }	/* sys_wait4 */
[62] = { 2, {ST, INT}, {ST, INT} }	/* sys_kill */
[63] = { 1, {PT, STRUCT OLD_UTSNAME} }	/* sys_uname */
[64] = { 3, {ST, KEY_T}, {ST, INT}, {ST, INT} }	/* sys_semget */
[65] = { 3, {ST, INT}, {PT, STRUCT SEMBUF}, {ST, UNSIGNED} }	/* sys_semop */
[66] = { 4, {ST, INT}, {ST, INT}, {ST, INT}, {ST, UNSIGNED LONG} }	/* sys_semctl */
[67] = { 1, {PT, CHAR} }	/* sys_shmdt */
[68] = { 2, {ST, KEY_T}, {ST, INT} }	/* sys_msgget */
[69] = { 4, {ST, INT}, {PT, STRUCT MSGBUF}, {ST, SIZE_T}, {ST, INT} }	/* sys_msgsnd */
[70] = { 5, {ST, INT}, {PT, STRUCT MSGBUF}, {ST, SIZE_T}, {ST, LONG}, {ST, INT} }	/* sys_msgrcv */
[71] = { 3, {ST, INT}, {ST, INT}, {PT, STRUCT MSQID_DS} }	/* sys_msgctl */
[72] = { 3, {ST, UNSIGNED INT}, {ST, UNSIGNED INT}, {ST, UNSIGNED LONG} }	/* sys_fcntl */
[73] = { 2, {ST, UNSIGNED INT}, {ST, UNSIGNED INT} }	/* sys_flock */
[74] = { 1, {ST, UNSIGNED INT} }	/* sys_fsync */
[75] = { 1, {ST, UNSIGNED INT} }	/* sys_fdatasync */
[76] = { 2, {PT, CHAR}, {ST, LONG} }	/* sys_truncate */
[77] = { 2, {ST, UNSIGNED INT}, {ST, UNSIGNED LONG} }	/* sys_ftruncate */
[78] = { 3, {ST, UNSIGNED INT}, {PT, STRUCT LINUX_DIRENT}, {ST, UNSIGNED INT} }	/* sys_getdents */
[79] = { 2, {PT, CHAR}, {ST, UNSIGNED LONG} }	/* sys_getcwd */
[80] = { 1, {PT, CHAR} }	/* sys_chdir */
[81] = { 1, {ST, UNSIGNED INT} }	/* sys_fchdir */
[82] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys_rename */
[83] = { 2, {PT, CHAR}, {ST, UMODE_T} }	/* sys_mkdir */
[84] = { 1, {PT, CHAR} }	/* sys_rmdir */
[85] = { 2, {PT, CHAR}, {ST, UMODE_T} }	/* sys_creat */
[86] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys_link */
[87] = { 1, {PT, CHAR} }	/* sys_unlink */
[88] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys_symlink */
[89] = { 3, {PT, CHAR}, {PT, CHAR}, {ST, INT} }	/* sys_readlink */
[90] = { 2, {PT, CHAR}, {ST, UMODE_T} }	/* sys_chmod */
[91] = { 2, {ST, UNSIGNED INT}, {ST, UMODE_T} }	/* sys_fchmod */
[92] = { 3, {PT, CHAR}, {ST, UID_T}, {ST, GID_T} }	/* sys_chown */
[93] = { 3, {ST, UNSIGNED INT}, {ST, UID_T}, {ST, GID_T} }	/* sys_fchown */
[94] = { 3, {PT, CHAR}, {ST, UID_T}, {ST, GID_T} }	/* sys_lchown */
[95] = { 1, {ST, INT} }	/* sys_umask */
[96] = { 2, {PT, STRUCT TIMEVAL}, {PT, STRUCT TIMEZONE} }	/* sys_gettimeofday */
[97] = { 2, {ST, UNSIGNED INT}, {PT, STRUCT RLIMIT} }	/* sys_getrlimit */
[98] = { 2, {ST, INT}, {PT, STRUCT RUSAGE} }	/* sys_getrusage */
[99] = { 1, {PT, STRUCT SYSINFO} }	/* sys_sysinfo */
[100] = { 1, {PT, STRUCT TMS} }	/* sys_times */
[101] = { 4, {ST, LONG}, {ST, LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_ptrace */
[102] = { 1, {ST, VOID} }	/* sys_getuid */
[103] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_syslog */
[104] = { 1, {ST, VOID} }	/* sys_getgid */
[105] = { 1, {ST, UID_T} }	/* sys_setuid */
[106] = { 1, {ST, GID_T} }	/* sys_setgid */
[107] = { 1, {ST, VOID} }	/* sys_geteuid */
[108] = { 1, {ST, VOID} }	/* sys_getegid */
[109] = { 2, {ST, PID_T}, {ST, PID_T} }	/* sys_setpgid */
[110] = { 1, {ST, VOID} }	/* sys_getppid */
[111] = { 1, {ST, VOID} }	/* sys_getpgrp */
[112] = { 1, {ST, VOID} }	/* sys_setsid */
[113] = { 2, {ST, UID_T}, {ST, UID_T} }	/* sys_setreuid */
[114] = { 2, {ST, GID_T}, {ST, GID_T} }	/* sys_setregid */
[115] = { 2, {ST, INT}, {PT, GID_T} }	/* sys_getgroups */
[116] = { 2, {ST, INT}, {PT, GID_T} }	/* sys_setgroups */
[117] = { 3, {ST, UID_T}, {ST, UID_T}, {ST, UID_T} }	/* sys_setresuid */
[118] = { 3, {PT, UID_T}, {PT, UID_T}, {PT, UID_T} }	/* sys_getresuid */
[119] = { 3, {ST, GID_T}, {ST, GID_T}, {ST, GID_T} }	/* sys_setresgid */
[120] = { 3, {PT, GID_T}, {PT, GID_T}, {PT, GID_T} }	/* sys_getresgid */
[121] = { 1, {ST, PID_T} }	/* sys_getpgid */
[122] = { 1, {ST, UID_T} }	/* sys_setfsuid */
[123] = { 1, {ST, GID_T} }	/* sys_setfsgid */
[124] = { 1, {ST, PID_T} }	/* sys_getsid */
[125] = { 2, {ST, CAP_USER_HEADER_T}, {ST, CAP_USER_DATA_T} }	/* sys_capget */
[126] = { 2, {ST, CAP_USER_HEADER_T}, {ST, CAP_USER_DATA_T} }	/* sys_capset */
[127] = { 2, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_rt_sigpending */
[128] = { 4, {PT, SIGSET_T}, {PT, SIGINFO_T}, {PT, STRUCT TIMESPEC}, {ST, SIZE_T} }	/* sys_rt_sigtimedwait */
[129] = { 3, {ST, INT}, {ST, INT}, {PT, SIGINFO_T} }	/* sys_rt_sigqueueinfo */
[130] = { 2, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_rt_sigsuspend */
[131] = { 2, {PT, STRUCT SIGALTSTACK}, {PT, STRUCT SIGALTSTACK} }	/* sys_sigaltstack */
[132] = { 2, {PT, CHAR}, {PT, STRUCT UTIMBUF} }	/* sys_utime */
[133] = { 3, {PT, CHAR}, {ST, UMODE_T}, {ST, UNSIGNED} }	/* sys_mknod */
[134] = { 1, {PT, CHAR} }	/* sys_uselib */
[135] = { 1, {ST, UNSIGNED INT} }	/* sys_personality */
[136] = { 2, {ST, UNSIGNED}, {PT, STRUCT USTAT} }	/* sys_ustat */
[137] = { 2, {PT, CHAR}, {PT, STRUCT STATFS} }	/* sys_statfs */
[138] = { 2, {ST, UNSIGNED INT}, {PT, STRUCT STATFS} }	/* sys_fstatfs */
[139] = { 3, {ST, INT}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_sysfs */
[140] = { 2, {ST, INT}, {ST, INT} }	/* sys_getpriority */
[141] = { 3, {ST, INT}, {ST, INT}, {ST, INT} }	/* sys_setpriority */
[142] = { 2, {ST, PID_T}, {PT, STRUCT SCHED_PARAM} }	/* sys_sched_setparam */
[143] = { 2, {ST, PID_T}, {PT, STRUCT SCHED_PARAM} }	/* sys_sched_getparam */
[144] = { 3, {ST, PID_T}, {ST, INT}, {PT, STRUCT SCHED_PARAM} }	/* sys_sched_setscheduler */
[145] = { 1, {ST, PID_T} }	/* sys_sched_getscheduler */
[146] = { 1, {ST, INT} }	/* sys_sched_get_priority_max */
[147] = { 1, {ST, INT} }	/* sys_sched_get_priority_min */
[148] = { 2, {ST, PID_T}, {PT, STRUCT TIMESPEC} }	/* sys_sched_rr_get_interval */
[149] = { 2, {ST, UNSIGNED LONG}, {ST, SIZE_T} }	/* sys_mlock */
[150] = { 2, {ST, UNSIGNED LONG}, {ST, SIZE_T} }	/* sys_munlock */
[151] = { 1, {ST, INT} }	/* sys_mlockall */
[152] = { 1, {ST, VOID} }	/* sys_munlockall */
[153] = { 1, {ST, VOID} }	/* sys_vhangup */
[154] = { 1, {ST, VOID} }	/* sys_modify_ldt */
[155] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys_pivot_root */
[156] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys__sysctl */
[157] = { 5, {ST, INT}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_prctl */
[158] = { 5, {ST, INT}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_arch_prctl */
[159] = { 1, {PT, STRUCT TIMEX} }	/* sys_adjtimex */
[160] = { 2, {ST, UNSIGNED INT}, {PT, STRUCT RLIMIT} }	/* sys_setrlimit */
[161] = { 1, {PT, CHAR} }	/* sys_chroot */
[162] = { 1, {ST, VOID} }	/* sys_sync */
[163] = { 1, {PT, CHAR} }	/* sys_acct */
[164] = { 2, {PT, STRUCT TIMEVAL}, {PT, STRUCT TIMEZONE} }	/* sys_settimeofday */
[165] = { 5, {PT, CHAR}, {PT, CHAR}, {PT, CHAR}, {ST, UNSIGNED LONG}, {PT, VOID} }	/* sys_mount */
[166] = { 5, {PT, CHAR}, {PT, CHAR}, {PT, CHAR}, {ST, UNSIGNED LONG}, {PT, VOID} }	/* sys_umount2 */
[167] = { 2, {PT, CHAR}, {ST, INT} }	/* sys_swapon */
[168] = { 1, {PT, CHAR} }	/* sys_swapoff */
[169] = { 4, {ST, INT}, {ST, INT}, {ST, UNSIGNED INT}, {PT, VOID} }	/* sys_reboot */
[170] = { 2, {PT, CHAR}, {ST, INT} }	/* sys_sethostname */
[171] = { 2, {PT, CHAR}, {ST, INT} }	/* sys_setdomainname */
[172] = { 2, {PT, CHAR}, {ST, INT} }	/* sys_iopl */
[173] = { 3, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, INT} }	/* sys_ioperm */
[174] = { 3, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, INT} }	/* sys_create_module */
[175] = { 3, {PT, VOID}, {ST, UNSIGNED LONG}, {PT, CHAR} }	/* sys_init_module */
[176] = { 2, {PT, CHAR}, {ST, UNSIGNED INT} }	/* sys_delete_module */
[177] = { 2, {PT, CHAR}, {ST, UNSIGNED INT} }	/* sys_get_kernel_syms */
[178] = { 2, {PT, CHAR}, {ST, UNSIGNED INT} }	/* sys_query_module */
[179] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_quotactl */
[180] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_nfsservctl */
[181] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_getpmsg */
[182] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_putpmsg */
[183] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_afs_syscall */
[184] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_tuxcall */
[185] = { 4, {ST, UNSIGNED INT}, {PT, CHAR}, {ST, QID_T}, {PT, VOID} }	/* sys_security */
[186] = { 1, {ST, VOID} }	/* sys_gettid */
[187] = { 3, {ST, INT}, {ST, LOFF_T}, {ST, SIZE_T} }	/* sys_readahead */
[188] = { 5, {PT, CHAR}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T}, {ST, INT} }	/* sys_setxattr */
[189] = { 5, {PT, CHAR}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T}, {ST, INT} }	/* sys_lsetxattr */
[190] = { 5, {ST, INT}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T}, {ST, INT} }	/* sys_fsetxattr */
[191] = { 4, {PT, CHAR}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T} }	/* sys_getxattr */
[192] = { 4, {PT, CHAR}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T} }	/* sys_lgetxattr */
[193] = { 4, {ST, INT}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T} }	/* sys_fgetxattr */
[194] = { 3, {PT, CHAR}, {PT, CHAR}, {ST, SIZE_T} }	/* sys_listxattr */
[195] = { 3, {PT, CHAR}, {PT, CHAR}, {ST, SIZE_T} }	/* sys_llistxattr */
[196] = { 3, {ST, INT}, {PT, CHAR}, {ST, SIZE_T} }	/* sys_flistxattr */
[197] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys_removexattr */
[198] = { 2, {PT, CHAR}, {PT, CHAR} }	/* sys_lremovexattr */
[199] = { 2, {ST, INT}, {PT, CHAR} }	/* sys_fremovexattr */
[200] = { 2, {ST, INT}, {ST, INT} }	/* sys_tkill */
[201] = { 1, {PT, TIME_T} }	/* sys_time */
[202] = { 6, {PT, U32}, {ST, INT}, {ST, U32}, {PT, STRUCT TIMESPEC}, {PT, U32}, {ST, U32} }	/* sys_futex */
[203] = { 3, {ST, PID_T}, {ST, UNSIGNED INT}, {PT, UNSIGNED LONG} }	/* sys_sched_setaffinity */
[204] = { 3, {ST, PID_T}, {ST, UNSIGNED INT}, {PT, UNSIGNED LONG} }	/* sys_sched_getaffinity */
[205] = { 3, {ST, PID_T}, {ST, UNSIGNED INT}, {PT, UNSIGNED LONG} }	/* sys_set_thread_area */
[206] = { 2, {ST, UNSIGNED}, {PT, AIO_CONTEXT_T} }	/* sys_io_setup */
[207] = { 1, {ST, AIO_CONTEXT_T} }	/* sys_io_destroy */
[208] = { 5, {ST, AIO_CONTEXT_T}, {ST, LONG}, {ST, LONG}, {PT, STRUCT IO_EVENT}, {PT, STRUCT TIMESPEC} }	/* sys_io_getevents */
[209] = { 3, {ST, AIO_CONTEXT_T}, {ST, LONG}, {PT, STRUCT IOCB} }	/* sys_io_submit */
[210] = { 3, {ST, AIO_CONTEXT_T}, {PT, STRUCT IOCB}, {PT, STRUCT IO_EVENT} }	/* sys_io_cancel */
[211] = { 3, {ST, AIO_CONTEXT_T}, {PT, STRUCT IOCB}, {PT, STRUCT IO_EVENT} }	/* sys_get_thread_area */
[212] = { 3, {ST, U64}, {PT, CHAR}, {ST, SIZE_T} }	/* sys_lookup_dcookie */
[213] = { 1, {ST, INT} }	/* sys_epoll_create */
[214] = { 1, {ST, INT} }	/* sys_epoll_ctl_old */
[215] = { 1, {ST, INT} }	/* sys_epoll_wait_old */
[216] = { 5, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_remap_file_pages */
[217] = { 3, {ST, UNSIGNED INT}, {PT, STRUCT LINUX_DIRENT64}, {ST, UNSIGNED INT} }	/* sys_getdents64 */
[218] = { 1, {PT, INT} }	/* sys_set_tid_address */
[219] = { 1, {ST, VOID} }	/* sys_restart_syscall */
[220] = { 4, {ST, INT}, {PT, STRUCT SEMBUF}, {ST, UNSIGNED}, {PT, STRUCT TIMESPEC} }	/* sys_semtimedop */
[221] = { 4, {ST, INT}, {ST, LOFF_T}, {ST, SIZE_T}, {ST, INT} }	/* sys_fadvise64 */
[222] = { 3, {ST, CLOCKID_T}, {PT, STRUCT SIGEVENT}, {PT, TIMER_T} }	/* sys_timer_create */
[223] = { 4, {ST, TIMER_T}, {ST, INT}, {PT, STRUCT ITIMERSPEC}, {PT, STRUCT ITIMERSPEC} }	/* sys_timer_settime */
[224] = { 2, {ST, TIMER_T}, {PT, STRUCT ITIMERSPEC} }	/* sys_timer_gettime */
[225] = { 1, {ST, TIMER_T} }	/* sys_timer_getoverrun */
[226] = { 1, {ST, TIMER_T} }	/* sys_timer_delete */
[227] = { 2, {ST, CLOCKID_T}, {PT, STRUCT TIMESPEC} }	/* sys_clock_settime */
[228] = { 2, {ST, CLOCKID_T}, {PT, STRUCT TIMESPEC} }	/* sys_clock_gettime */
[229] = { 2, {ST, CLOCKID_T}, {PT, STRUCT TIMESPEC} }	/* sys_clock_getres */
[230] = { 4, {ST, CLOCKID_T}, {ST, INT}, {PT, STRUCT TIMESPEC}, {PT, STRUCT TIMESPEC} }	/* sys_clock_nanosleep */
[231] = { 1, {ST, INT} }	/* sys_exit_group */
[232] = { 4, {ST, INT}, {PT, STRUCT EPOLL_EVENT}, {ST, INT}, {ST, INT} }	/* sys_epoll_wait */
[233] = { 4, {ST, INT}, {ST, INT}, {ST, INT}, {PT, STRUCT EPOLL_EVENT} }	/* sys_epoll_ctl */
[234] = { 3, {ST, INT}, {ST, INT}, {ST, INT} }	/* sys_tgkill */
[235] = { 2, {PT, CHAR}, {PT, STRUCT TIMEVAL} }	/* sys_utimes */
[236] = { 2, {PT, CHAR}, {PT, STRUCT TIMEVAL} }	/* sys_vserver */
[237] = { 6, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {PT, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED} }	/* sys_mbind */
[238] = { 3, {ST, INT}, {PT, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_set_mempolicy */
[239] = { 5, {PT, INT}, {PT, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_get_mempolicy */
[240] = { 4, {PT, CHAR}, {ST, INT}, {ST, UMODE_T}, {PT, STRUCT MQ_ATTR} }	/* sys_mq_open */
[241] = { 1, {PT, CHAR} }	/* sys_mq_unlink */
[242] = { 5, {ST, MQD_T}, {PT, CHAR}, {ST, SIZE_T}, {ST, UNSIGNED INT}, {PT, STRUCT TIMESPEC} }	/* sys_mq_timedsend */
[243] = { 5, {ST, MQD_T}, {PT, CHAR}, {ST, SIZE_T}, {PT, UNSIGNED INT}, {PT, STRUCT TIMESPEC} }	/* sys_mq_timedreceive */
[244] = { 2, {ST, MQD_T}, {PT, STRUCT SIGEVENT} }	/* sys_mq_notify */
[245] = { 3, {ST, MQD_T}, {PT, STRUCT MQ_ATTR}, {PT, STRUCT MQ_ATTR} }	/* sys_mq_getsetattr */
[246] = { 4, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {PT, STRUCT KEXEC_SEGMENT}, {ST, UNSIGNED LONG} }	/* sys_kexec_load */
[247] = { 5, {ST, INT}, {ST, PID_T}, {PT, STRUCT SIGINFO}, {ST, INT}, {PT, STRUCT RUSAGE} }	/* sys_waitid */
[248] = { 5, {PT, CHAR}, {PT, CHAR}, {PT, VOID}, {ST, SIZE_T}, {ST, KEY_SERIAL_T} }	/* sys_add_key */
[249] = { 4, {PT, CHAR}, {PT, CHAR}, {PT, CHAR}, {ST, KEY_SERIAL_T} }	/* sys_request_key */
[250] = { 5, {ST, INT}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_keyctl */
[251] = { 3, {ST, INT}, {ST, INT}, {ST, INT} }	/* sys_ioprio_set */
[252] = { 2, {ST, INT}, {ST, INT} }	/* sys_ioprio_get */
[253] = { 1, {ST, VOID} }	/* sys_inotify_init */
[254] = { 3, {ST, INT}, {PT, CHAR}, {ST, U32} }	/* sys_inotify_add_watch */
[255] = { 2, {ST, INT}, {ST, __S32} }	/* sys_inotify_rm_watch */
[256] = { 4, {ST, PID_T}, {ST, UNSIGNED LONG}, {PT, UNSIGNED LONG}, {PT, UNSIGNED LONG} }	/* sys_migrate_pages */
[257] = { 4, {ST, INT}, {PT, CHAR}, {ST, INT}, {ST, UMODE_T} }	/* sys_openat */
[258] = { 3, {ST, INT}, {PT, CHAR}, {ST, UMODE_T} }	/* sys_mkdirat */
[259] = { 4, {ST, INT}, {PT, CHAR}, {ST, UMODE_T}, {ST, UNSIGNED} }	/* sys_mknodat */
[260] = { 5, {ST, INT}, {PT, CHAR}, {ST, UID_T}, {ST, GID_T}, {ST, INT} }	/* sys_fchownat */
[261] = { 3, {ST, INT}, {PT, CHAR}, {PT, STRUCT TIMEVAL} }	/* sys_futimesat */
[262] = { 4, {ST, INT}, {PT, CHAR}, {PT, STRUCT STAT}, {ST, INT} }	/* sys_newfstatat */
[263] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_unlinkat */
[264] = { 4, {ST, INT}, {PT, CHAR}, {ST, INT}, {PT, CHAR} }	/* sys_renameat */
[265] = { 5, {ST, INT}, {PT, CHAR}, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_linkat */
[266] = { 3, {PT, CHAR}, {ST, INT}, {PT, CHAR} }	/* sys_symlinkat */
[267] = { 4, {ST, INT}, {PT, CHAR}, {PT, CHAR}, {ST, INT} }	/* sys_readlinkat */
[268] = { 3, {ST, INT}, {PT, CHAR}, {ST, UMODE_T} }	/* sys_fchmodat */
[269] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_faccessat */
[270] = { 6, {ST, INT}, {PT, FD_SET}, {PT, FD_SET}, {PT, FD_SET}, {PT, STRUCT TIMESPEC}, {PT, VOID} }	/* sys_pselect6 */
[271] = { 5, {PT, STRUCT POLLFD}, {ST, UNSIGNED INT}, {PT, STRUCT TIMESPEC}, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_ppoll */
[272] = { 1, {ST, UNSIGNED LONG} }	/* sys_unshare */
[273] = { 2, {PT, STRUCT ROBUST_LIST_HEAD}, {ST, SIZE_T} }	/* sys_set_robust_list */
[274] = { 3, {ST, INT}, {PT, STRUCT ROBUST_LIST_HEAD}, {PT, SIZE_T} }	/* sys_get_robust_list */
[275] = { 6, {ST, INT}, {PT, LOFF_T}, {ST, INT}, {PT, LOFF_T}, {ST, SIZE_T}, {ST, UNSIGNED INT} }	/* sys_splice */
[276] = { 4, {ST, INT}, {ST, INT}, {ST, SIZE_T}, {ST, UNSIGNED INT} }	/* sys_tee */
[277] = { 4, {ST, INT}, {ST, LOFF_T}, {ST, LOFF_T}, {ST, UNSIGNED INT} }	/* sys_sync_file_range */
[278] = { 4, {ST, INT}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {ST, UNSIGNED INT} }	/* sys_vmsplice */
[279] = { 6, {ST, PID_T}, {ST, UNSIGNED LONG}, {PT, VOID}, {PT, INT}, {PT, INT}, {ST, INT} }	/* sys_move_pages */
[280] = { 4, {ST, INT}, {PT, CHAR}, {PT, STRUCT TIMESPEC}, {ST, INT} }	/* sys_utimensat */
[281] = { 6, {ST, INT}, {PT, STRUCT EPOLL_EVENT}, {ST, INT}, {ST, INT}, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_epoll_pwait */
[282] = { 3, {ST, INT}, {PT, SIGSET_T}, {ST, SIZE_T} }	/* sys_signalfd */
[283] = { 2, {ST, INT}, {ST, INT} }	/* sys_timerfd_create */
[284] = { 1, {ST, UNSIGNED INT} }	/* sys_eventfd */
[285] = { 4, {ST, INT}, {ST, INT}, {ST, LOFF_T}, {ST, LOFF_T} }	/* sys_fallocate */
[286] = { 4, {ST, INT}, {ST, INT}, {PT, STRUCT ITIMERSPEC}, {PT, STRUCT ITIMERSPEC} }	/* sys_timerfd_settime */
[287] = { 2, {ST, INT}, {PT, STRUCT ITIMERSPEC} }	/* sys_timerfd_gettime */
[288] = { 4, {ST, INT}, {PT, STRUCT SOCKADDR}, {PT, INT}, {ST, INT} }	/* sys_accept4 */
[289] = { 4, {ST, INT}, {PT, SIGSET_T}, {ST, SIZE_T}, {ST, INT} }	/* sys_signalfd4 */
[290] = { 2, {ST, UNSIGNED INT}, {ST, INT} }	/* sys_eventfd2 */
[291] = { 1, {ST, INT} }	/* sys_epoll_create1 */
[292] = { 3, {ST, UNSIGNED INT}, {ST, UNSIGNED INT}, {ST, INT} }	/* sys_dup3 */
[293] = { 2, {PT, INT}, {ST, INT} }	/* sys_pipe2 */
[294] = { 1, {ST, INT} }	/* sys_inotify_init1 */
[295] = { 5, {ST, UNSIGNED LONG}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_preadv */
[296] = { 5, {ST, UNSIGNED LONG}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_pwritev */
[297] = { 4, {ST, PID_T}, {ST, PID_T}, {ST, INT}, {PT, SIGINFO_T} }	/* sys_rt_tgsigqueueinfo */
[298] = { 5, {PT, STRUCT PERF_EVENT_ATTR}, {ST, PID_T}, {ST, INT}, {ST, INT}, {ST, UNSIGNED LONG} }	/* sys_perf_event_open */
[299] = { 5, {ST, INT}, {PT, STRUCT MMSGHDR}, {ST, UNSIGNED INT}, {ST, UNSIGNED}, {PT, STRUCT TIMESPEC} }	/* sys_recvmmsg */
[300] = { 2, {ST, UNSIGNED INT}, {ST, UNSIGNED INT} }	/* sys_fanotify_init */
[301] = { 5, {ST, INT}, {ST, UNSIGNED INT}, {ST, U64}, {ST, INT}, {PT, CHAR} }	/* sys_fanotify_mark */
[302] = { 4, {ST, PID_T}, {ST, UNSIGNED INT}, {PT, STRUCT RLIMIT64}, {PT, STRUCT RLIMIT64} }	/* sys_prlimit64 */
[303] = { 5, {ST, INT}, {PT, CHAR}, {PT, STRUCT FILE_HANDLE}, {PT, INT}, {ST, INT} }	/* sys_name_to_handle_at */
[304] = { 3, {ST, INT}, {PT, STRUCT FILE_HANDLE}, {ST, INT} }	/* sys_open_by_handle_at */
[305] = { 2, {ST, CLOCKID_T}, {PT, STRUCT TIMEX} }	/* sys_clock_adjtime */
[306] = { 1, {ST, INT} }	/* sys_syncfs */
[307] = { 4, {ST, INT}, {PT, STRUCT MMSGHDR}, {ST, UNSIGNED INT}, {ST, UNSIGNED} }	/* sys_sendmmsg */
[308] = { 2, {ST, INT}, {ST, INT} }	/* sys_setns */
[309] = { 3, {PT, UNSIGNED}, {PT, UNSIGNED}, {PT, STRUCT GETCPU_CACHE} }	/* sys_getcpu */
[310] = { 6, {ST, PID_T}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_process_vm_readv */
[311] = { 6, {ST, PID_T}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {PT, STRUCT IOVEC}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_process_vm_writev */
[312] = { 5, {ST, PID_T}, {ST, PID_T}, {ST, INT}, {ST, UNSIGNED LONG}, {ST, UNSIGNED LONG} }	/* sys_kcmp */
[313] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_finit_module */
[314] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_sched_setattr */
[315] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_sched_getattr */
[316] = { 3, {ST, INT}, {PT, CHAR}, {ST, INT} }	/* sys_renameat2 */
[317] = { 3, {ST, UNSIGNED INT}, {ST, UNSIGNED INT}, {PT, CHAR} }	/* sys_seccomp */
